# Generated by Django 6.0 on 2026-01-10 13:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "url",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                (
                    "monitor_type",
                    models.CharField(
                        choices=[("HTTP", "HTTP(s)"), ("PING", "PING"), ("TCP", "TCP")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("UP", "UP"), ("DOWN", "DOWN"), ("PAUSED", "PAUSED")],
                        default="PAUSED",
                        max_length=10,
                    ),
                ),
                (
                    "interval",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[django.core.validators.MinValueValidator(30)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitor",
                "verbose_name_plural": "Monitors",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="monitor_mon_user_id_1ac92e_idx",
                    )
                ],
            },
        ),
    ]
