# Generated by Django 6.0 on 2026-01-12 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="interval",
            field=models.PositiveIntegerField(
                default=300, validators=[django.core.validators.MinValueValidator(30)]
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="url",
            field=models.URLField(
                max_length=2048, validators=[django.core.validators.URLValidator()]
            ),
        ),
    ]
