# Generated by Django 6.0 on 2026-01-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0003_monitorresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
