# Generated by Django 6.0 on 2026-01-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0004_monitor_last_checked_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="monitorresult",
            index=models.Index(
                fields=["monitor", "-created_at"], name="monitor_mon_monitor_048459_idx"
            ),
        ),
    ]
