# Generated by Django 6.0 on 2026-01-12 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_alter_monitor_interval_alter_monitor_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitorResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_up", models.BooleanField()),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="monitor.monitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitor Result",
                "verbose_name_plural": "Monitor Results",
                "ordering": ("-checked_at",),
                "indexes": [
                    models.Index(
                        fields=["monitor", "checked_at"],
                        name="monitor_mon_monitor_715b35_idx",
                    )
                ],
            },
        ),
    ]
