# Generated by Django 6.0 on 2026-01-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationchannel",
            name="provider",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("slack", "Slack"),
                    ("telegram", "Telegram"),
                    ("console", "Console (Debug)"),
                ],
                max_length=20,
            ),
        ),
    ]
